# Generated by Django 5.2.13 on 2026-04-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=15)),
                ('hobbies', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='images/')),
                ('password', models.CharField(max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=200)),
            ],
        ),
    ]
