# Generated by Django 5.2.13 on 2026-04-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='Trivandrum', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(max_length=25),
        ),
    ]
