# Generated by Django 5.2.13 on 2026-04-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_country_student_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, to='student.course'),
        ),
    ]
