# Generated by Django 5.2.13 on 2026-04-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='temp_password_sent',
            field=models.BooleanField(default=False),
        ),
    ]
